name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.3.0
      - name: Install app dependencies
        run: "npm install"
      - name: Initialize .env
        run: printf "${{ secrets.ENV }}" > .env
      - name: Build the app
        run: "npm run electron:build"
